### ISSUE TITLE
[Feature Request] Add optional patch to fix the dice texture so that it is better readable in event square descriptions

### ISSUE THREAD

**Issue by Deflaktor** [FortuneStreetModding/csmm-qt#21]

**Comment by MysticMismagius** [comment]
I happen to have a Mario Party themed die texture, and my special characters texture (which is the texture for the die in the descriptions) looks like this:

<p align="center"><img src="https://i.imgur.com/vBmsW8R.png"></p>

It has a transparent background because any opaque pixel in the die special characters will be darkened significantly in the description on the white text-boxes. This alteration does not occur in the description when hovering over the Event Square.

Here's how this distinction looks in practice:

Hovering over the square:
<p align="center"><img src="https://i.imgur.com/2NJt4b6.png"width="675"></p>

White Text box:

<p align="center"><img src="https://i.imgur.com/obVMJYW.png"width="675"></p>None of the pixels here are quite black, but you won't notice this in practice unless you're really looking for it. With that said, if you happen to have an opaque white pixel in this texture, it will appear as a medium gray, which I wouldn't recommend.

I'd suggest making a die texture that is colored, not white or black. Make sure the color is light enough that it is visible in the fairly dark textbox of the square description, but not so light that it is almost white. The lightest color in my texture is #B5B5DE, which appears as roughly #232334 in the white text box.

**Comment by Deflaktor** [comment]
Thanks for the hint. I still cant find the texture file in the game files though. I wonder where the game stores the dice image.

**Comment by Deflaktor** [comment]
Fixed with ad9289d58669f2cf44ff3e1ebbd7bdbf6e51e616
